/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RespeckData
 */
export interface RespeckData {
    /**
     * 
     * @type {Array<Array<number>>}
     * @memberof RespeckData
     */
    respeckData?: Array<Array<number>>;
}

export function RespeckDataFromJSON(json: any): RespeckData {
    return RespeckDataFromJSONTyped(json, false);
}

export function RespeckDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): RespeckData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'respeckData': !exists(json, 'respeck_data') ? undefined : json['respeck_data'],
    };
}

export function RespeckDataToJSON(value?: RespeckData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'respeck_data': value.respeckData,
    };
}


