/**
* API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 * @param predictions 
 * @param label 
 * @param activity 
 */

data class RespeckPrediction (
    @SerializedName("predictions")
    val predictions: kotlin.collections.List<java.math.BigDecimal>? = null,
    @SerializedName("label")
    val label: kotlin.Int? = null,
    @SerializedName("activity")
    val activity: kotlin.String? = null
)

