/**
* API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 * @param respeckData 
 */

data class RespeckData (
    @SerializedName("respeck_data")
    val respeckData: kotlin.collections.List<kotlin.collections.List<java.math.BigDecimal>>? = null
)

