/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.math.BigDecimal;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class RespeckData {
  
  @SerializedName("respeck_data")
  private List<List<BigDecimal>> respeckData = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public List<List<BigDecimal>> getRespeckData() {
    return respeckData;
  }
  public void setRespeckData(List<List<BigDecimal>> respeckData) {
    this.respeckData = respeckData;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RespeckData respeckData = (RespeckData) o;
    return (this.respeckData == null ? respeckData.respeckData == null : this.respeckData.equals(respeckData.respeckData));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.respeckData == null ? 0: this.respeckData.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class RespeckData {\n");
    
    sb.append("  respeckData: ").append(respeckData).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
