/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.math.BigDecimal;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class RespeckPrediction {
  
  @SerializedName("predictions")
  private List<BigDecimal> predictions = null;
  @SerializedName("label")
  private Integer label = null;
  @SerializedName("activity")
  private String activity = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public List<BigDecimal> getPredictions() {
    return predictions;
  }
  public void setPredictions(List<BigDecimal> predictions) {
    this.predictions = predictions;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getLabel() {
    return label;
  }
  public void setLabel(Integer label) {
    this.label = label;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getActivity() {
    return activity;
  }
  public void setActivity(String activity) {
    this.activity = activity;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RespeckPrediction respeckPrediction = (RespeckPrediction) o;
    return (this.predictions == null ? respeckPrediction.predictions == null : this.predictions.equals(respeckPrediction.predictions)) &&
        (this.label == null ? respeckPrediction.label == null : this.label.equals(respeckPrediction.label)) &&
        (this.activity == null ? respeckPrediction.activity == null : this.activity.equals(respeckPrediction.activity));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.predictions == null ? 0: this.predictions.hashCode());
    result = 31 * result + (this.label == null ? 0: this.label.hashCode());
    result = 31 * result + (this.activity == null ? 0: this.activity.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class RespeckPrediction {\n");
    
    sb.append("  predictions: ").append(predictions).append("\n");
    sb.append("  label: ").append(label).append("\n");
    sb.append("  activity: ").append(activity).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
